### ISSUE TITLE
Want to contribute to this Repository

### ISSUE THREAD

**Issue by Alitindrawan24** [DumindUdara/Travel-Agency#2]
Hello @DumindUdara, I see this repository accept hacktoberfest contribution and I want to make some contribution to this repository. What I can support or help on this repository? Thank you.

**Comment by manulthanura** [comment]
Hi @Alitindrawan24 👋🏻, 

Thank you for being so interested in contributing to the repository. I am happy to see that you are excited about Hacktoberfest!

There are many ways that you can contribute to the repository. Here are a few ideas:

- Fix bugs. If you find any bugs in the code, please submit an issue or pull request to fix them.
- Add new features. If you have any ideas for new features that would be useful for the repository, please feel free to submit an issue or pull request.
- Improve documentation. If you find any areas where the documentation could be improved, please submit a pull request with your changes.
- Write tests. If the repository does not have many tests, please consider writing some. This will help to improve the quality of the code.

If you are new to contributing to open source, I recommend starting with a small task, such as fixing a typo or adding a test. As you gain more experience, you can take on more challenging tasks. Also, make sure every PR is assigned to me @manulthanura or @DumindUdara, and add the "Hacktoberfest" label.

**Comment by shrey141102** [comment]
I also want to contribute @manulthanura @DumindUdara

**Comment by manulthanura** [comment]
Hi @shrey141102  👋🏻,

Thank you for being so interested in contributing to the repository. I am happy to see that you are excited about Hacktoberfest!

There are many ways that you can contribute to the repository. Here are a few ideas:

Fix bugs. If you find any bugs in the code, please submit an issue or pull request to fix them.
Add new features. If you have any ideas for new features that would be useful for the repository, please feel free to submit an issue or pull request.
Improve documentation. If you find any areas where the documentation could be improved, please submit a pull request with your changes.
Write tests. If the repository does not have many tests, please consider writing some. This will help to improve the quality of the code.
If you are new to contributing to open source, I recommend starting with a small task, such as fixing a typo or adding a test. As you gain more experience, you can take on more challenging tasks. Also, make sure every PR is assigned to me @manulthanura or @DumindUdara, and add the "Hacktoberfest" label.
